// Copyright (c) 2014-2024 Zano Project
// Copyright (c) 2014-2018 The Louisdor Project
// Copyright (c) 2012-2013 The Cryptonote developers
// Distributed under the MIT/X11 software license, see the accompanying
// file COPYING or http://www.opensource.org/licenses/mit-license.php.

#pragma once

#include "chaingen.h"
#include "chaingen001.h"
#include "block_reward.h"
#include "block_validation.h"
#include "chain_split_1.h"
#include "chain_switch_1.h"
#include "double_spend.h"
#include "integer_overflow.h"
#include "ring_signature_1.h"
#include "tx_validation.h"
#include "alias_tests.h"
#include "mixin_attr.h"
#include "get_random_outs.h"
#include "pruning_ring_signatures.h"
#include "pos_basic_tests.h"
#include "cumulative_diificulty_adjustments_tests.h"
#include "offers_test.h"
#include "chain_switch_pow_pos.h"
#include "pos_validation.h"
#include "checkpoints_tests.h"
#include "wallet_tests.h"
#include "wallet_rpc_tests.h"
#include "multisig_wallet_tests.h"
#include "escrow_wallet_tests.h"
#include "escrow_wallet_altchain_test.h"
#include "misc_tests.h"
#include "emission_test.h"
#include "hard_fork_1_locked_pos_test.h"
#include "hard_fork_1_consensus_test.h"
#include "hard_fork_1_bad_pos_source.h"
#include "hard_fork_1.h"
#include "hard_fork_2.h"
#include "hard_fork_4.h"
#include "atomic_tests.h"
#include "isolate_auditable_and_proof.h"
#include "zarcanum_test.h"
#include "multiassets_test.h"
#include "ionic_swap_tests.h"
#include "attachment_isolation_encryption_test.h"
#include "pos_fuse_test.h"