#pragma once

#include <cstdint>
#include <limits>
#include <string_view>
#include <unordered_map>
#include <vector>

struct test_time_hint {
  std::string_view name;
  uint64_t ms;
};

// Aggregated per-test timings are written to: <run_root>/workers_report.json (default run_root is "chaingen_runs")
inline const std::vector<test_time_hint> k_test_time_hints = {
  {"gen_alias_tests @ HF 4", 102170},
  {"gen_alias_tests @ HF 5", 102154},
  {"gen_alias_tests @ HF 6", 102083},
  {"gen_alias_tests @ HF 3", 19867},
  {"gen_alias_too_many_regs_in_block_template @ HF 3", 19632},
  {"pos_and_no_pow_blocks_between_output_and_stake @ HF 4", 8235},
  {"pos_and_no_pow_blocks_between_output_and_stake @ HF 5", 8215},
  {"pos_and_no_pow_blocks_between_output_and_stake @ HF 6", 8152},
  {"gen_pos_basic_tests (BC saveload)", 5721},
  {"hard_fork_6_intrinsic_payment_id_rpc_test", 5057},
  {"multiassets_basic_test @ HF 4", 5029},
  {"multiassets_basic_test @ HF 5", 5026},
  {"multiassets_basic_test @ HF 6", 5015},
  {"gen_alias_too_small_reward @ HF 4", 4517},
  {"gen_alias_too_small_reward @ HF 5", 4508},
  {"gen_alias_too_small_reward @ HF 6", 4500},
  {"input_refers_to_incompatible_by_type_output", 4349},
  {"wallet_rpc_thirdparty_custody @ HF 5", 4026},
  {"wallet_rpc_thirdparty_custody @ HF 6", 4007},
  {"hard_fork_6_intrinsic_payment_id_basic_test", 3932},
  {"asset_operations_and_chain_switching @ HF 5", 3801},
  {"zarcanum_in_alt_chain", 3781},
  {"asset_operations_and_chain_switching @ HF 6", 3778},
  {"escrow_custom_test", 3707},
  {"asset_operations_and_chain_switching @ HF 4", 3672},
  {"pos_altblocks_validation @ HF 4", 3596},
  {"pos_altblocks_validation @ HF 6", 3575},
  {"pos_altblocks_validation @ HF 5", 3546},
  {"zarcanum_basic_test", 3530},
  {"wallet_true_rpc_pos_mining @ HF 4", 3521},
  {"zarcanum_gen_time_balance", 3504},
  {"wallet_rpc_cold_signing @ HF 6", 3450},
  {"wallet_rpc_cold_signing @ HF 5", 3436},
  {"gen_wallet_alias_and_unconfirmed_txs @ HF 5", 3433},
  {"gen_wallet_alias_and_unconfirmed_txs @ HF 6", 3424},
  {"gen_wallet_alias_and_unconfirmed_txs @ HF 4", 3407},
  {"tx_pool_validation_and_chain_switch @ HF 4", 3368},
  {"tx_pool_validation_and_chain_switch @ HF 5", 3348},
  {"gen_wallet_alias_via_special_wallet_funcs @ HF 4", 3063},
  {"gen_wallet_alias_via_special_wallet_funcs @ HF 5", 3048},
  {"ionic_swap_basic_test @ HF 4", 3035},
  {"ionic_swap_basic_test @ HF 6", 3029},
  {"block_reward_in_alt_chain_basic @ HF 5", 3026},
  {"gen_wallet_alias_via_special_wallet_funcs @ HF 6", 3022},
  {"ionic_swap_basic_test @ HF 5", 3021},
  {"block_reward_in_alt_chain_basic @ HF 6", 3005},
  {"assets_and_explicit_native_coins_in_outs", 3002},
  {"gen_alias_switch_and_check_block_template @ HF 4", 2995},
  {"gen_alias_switch_and_check_block_template @ HF 5", 2986},
  {"assets_transfer_with_smallest_amount @ HF 4", 2982},
  {"ionic_swap_exact_amounts_test @ HF 4", 2954},
  {"assets_transfer_with_smallest_amount @ HF 5", 2953},
  {"ionic_swap_exact_amounts_test @ HF 6", 2945},
  {"gen_alias_switch_and_check_block_template @ HF 6", 2942},
  {"ionic_swap_exact_amounts_test @ HF 5", 2924},
  {"gen_wallet_save_load_and_balance @ HF 6", 2840},
  {"wallet_reorganize_and_trim_test @ HF 5", 2835},
  {"wallet_reorganize_and_trim_test @ HF 6", 2832},
  {"hard_fork_2_auditable_addresses_basics @ HF 6", 2810},
  {"hard_fork_2_auditable_addresses_basics @ HF 4", 2795},
  {"hard_fork_2_auditable_addresses_basics @ HF 5", 2793},
  {"wallet_reorganize_and_trim_test @ HF 4", 2791},
  {"gen_wallet_save_load_and_balance @ HF 5", 2779},
  {"block_reward_in_main_chain_basic @ HF 4", 2766},
  {"gen_wallet_save_load_and_balance @ HF 4", 2757},
  {"block_reward_in_main_chain_basic @ HF 5", 2749},
  {"block_reward_in_main_chain_basic @ HF 6", 2728},
  {"asset_operation_in_consolidated_tx @ HF 5", 2667},
  {"asset_operation_in_consolidated_tx @ HF 6", 2665},
  {"asset_operation_in_consolidated_tx @ HF 4", 2659},
  {"zarcanum_pos_block_math", 2657},
  {"hard_fork_2_awo_wallets_basic_test<false>", 2613},
  {"block_choice_rule_bigger_fee @ HF 5", 2558},
  {"several_asset_emit_burn_txs_in_pool @ HF 5", 2557},
  {"block_reward_in_alt_chain_basic @ HF 4", 2544},
  {"block_choice_rule_bigger_fee @ HF 4", 2542},
  {"eth_signed_asset_via_rpc @ HF 5", 2540},
  {"eth_signed_asset_via_rpc @ HF 6", 2532},
  {"block_choice_rule_bigger_fee @ HF 6", 2528},
  {"asset_operation_and_hardfork_checks @ HF 4", 2523},
  {"several_asset_emit_burn_txs_in_pool @ HF 6", 2517},
  {"asset_operation_and_hardfork_checks @ HF 6", 2516},
  {"wallet_rpc_exchange_suite @ HF 4", 2504},
  {"asset_operation_and_hardfork_checks @ HF 5", 2487},
  {"assets_transfer_with_smallest_amount @ HF 6", 2472},
  {"gen_alias_strange_data @ HF 5", 2450},
  {"gen_alias_strange_data @ HF 4", 2438},
  {"chain_switching_when_out_spent_in_alt_chain_ref_id @ HF 6", 2435},
  {"chain_switching_when_out_spent_in_alt_chain_mixin @ HF 4", 2430},
  {"chain_switching_when_out_spent_in_alt_chain_ref_id @ HF 4", 2427},
  {"chain_switching_when_out_spent_in_alt_chain_ref_id @ HF 5", 2426},
  {"chain_switching_when_out_spent_in_alt_chain_mixin @ HF 5", 2425},
  {"gen_alias_strange_data @ HF 6", 2424},
  {"chain_switching_when_out_spent_in_alt_chain_mixin @ HF 6", 2405},
  {"gen_alias_same_alias_in_tx_pool @ HF 5", 2388},
  {"gen_alias_same_alias_in_tx_pool @ HF 6", 2381},
  {"gen_alias_same_alias_in_tx_pool @ HF 4", 2351},
  {"block_template_blacklist_test @ HF 5", 2348},
  {"block_template_blacklist_test @ HF 4", 2318},
  {"wallet_and_sweep_below @ HF 5", 2297},
  {"block_template_blacklist_test @ HF 6", 2284},
  {"gen_chain_switch_pow_pos", 2278},
  {"hardfork_4_wallet_transfer_with_mandatory_mixins @ HF 4", 2249},
  {"wallet_and_sweep_below @ HF 6", 2247},
  {"zarcanum_in_alt_chain_2 @ HF 4", 2242},
  {"hardfork_4_wallet_transfer_with_mandatory_mixins @ HF 6", 2237},
  {"wallet_and_sweep_below @ HF 4", 2226},
  {"hardfork_4_wallet_transfer_with_mandatory_mixins @ HF 5", 2218},
  {"gen_wallet_mine_pos_block @ HF 6", 2196},
  {"zarcanum_in_alt_chain_2 @ HF 6", 2194},
  {"escrow_incorrect_cancel_proposal", 2183},
  {"zarcanum_in_alt_chain_2 @ HF 5", 2181},
  {"alt_chain_and_block_tx_fee_median @ HF 5", 2124},
  {"alt_chain_and_block_tx_fee_median @ HF 4", 2107},
  {"hard_fork_4_consolidated_txs @ HF 5", 2106},
  {"alt_chain_and_block_tx_fee_median @ HF 6", 2102},
  {"isolate_auditable_and_proof @ HF 5", 2080},
  {"isolate_auditable_and_proof @ HF 6", 2079},
  {"hard_fork_4_consolidated_txs @ HF 6", 2077},
  {"escrow_wallet_test", 2076},
  {"hard_fork_5_tx_version @ HF 5", 2074},
  {"hard_fork_5_tx_version @ HF 6", 2071},
  {"tx_input_mixins", 2071},
  {"hard_fork_4_consolidated_txs @ HF 4", 2069},
  {"isolate_auditable_and_proof @ HF 4", 2056},
  {"hard_fork_2_awo_wallets_basic_test<true>", 2041},
  {"eth_signed_asset_basics @ HF 6", 2033},
  {"wallet_true_rpc_pos_mining @ HF 5", 2024},
  {"eth_signed_asset_basics @ HF 5", 2022},
  {"zarcanum_block_with_txs", 2019},
  {"gen_alias_switch_and_tx_pool @ HF 4", 2017},
  {"wallet_true_rpc_pos_mining @ HF 6", 2015},
  {"gen_alias_switch_and_tx_pool @ HF 5", 2014},
  {"gen_alias_switch_and_tx_pool @ HF 6", 2007},
  {"assets_and_pos_mining @ HF 6", 1937},
  {"assets_and_pos_mining @ HF 4", 1929},
  {"zarcanum_txs_with_big_shuffled_decoy_set_shuffled", 1892},
  {"pos_fuse_test @ HF 4", 1877},
  {"pos_fuse_test @ HF 5", 1827},
  {"pos_fuse_test @ HF 6", 1814},
  {"escrow_w_and_fake_outputs", 1730},
  {"gen_wallet_mine_pos_block @ HF 4", 1688},
  {"gen_alias_concurrency_with_switch @ HF 6", 1674},
  {"gen_wallet_mine_pos_block @ HF 5", 1672},
  {"gen_alias_concurrency_with_switch @ HF 5", 1668},
  {"escrow_incorrect_proposal", 1667},
  {"gen_alias_concurrency_with_switch @ HF 4", 1642},
  {"wallet_rpc_alias_tests", 1642},
  {"hardfork_4_wallet_sweep_bare_outs", 1595},
  {"asset_depoyment_and_few_zc_utxos", 1593},
  {"prun_ring_signatures", 1560},
  {"gen_block_is_too_big @ HF 3", 1544},
  {"gen_block_is_too_big @ HF 0", 1540},
  {"asset_emission_and_unconfirmed_balance @ HF 4", 1528},
  {"attachment_isolation_test @ HF 4", 1522},
  {"attachment_isolation_test @ HF 5", 1520},
  {"asset_emission_and_unconfirmed_balance @ HF 6", 1512},
  {"asset_emission_and_unconfirmed_balance @ HF 5", 1511},
  {"escrow_incorrect_proposal_acceptance", 1510},
  {"gen_block_ts_not_checked @ HF 3", 1494},
  {"gen_block_ts_in_past @ HF 0", 1455},
  {"assets_and_pos_mining @ HF 5", 1424},
  {"gen_block_ts_not_checked @ HF 0", 1387},
  {"pos_minting_tx_packing", 1387},
  {"gen_block_ts_in_past @ HF 3", 1363},
  {"multisig_wallet_test", 1351},
  {"multisig_wallet_test_many_dst", 1332},
  {"gen_alias_update_for_free @ HF 5", 1331},
  {"gen_alias_update_for_free @ HF 6", 1320},
  {"gen_alias_update_for_free @ HF 4", 1296},
  {"alt_blocks_validation_and_same_new_amount_in_two_txs @ HF 6", 1281},
  {"alt_blocks_validation_and_same_new_amount_in_two_txs @ HF 5", 1273},
  {"hard_fork_1_locked_mining_test", 1264},
  {"alt_blocks_validation_and_same_new_amount_in_two_txs @ HF 4", 1256},
  {"gen_simple_chain_001", 1256},
  {"block_with_correct_prev_id_on_wrong_height @ HF 6", 1254},
  {"alt_blocks_with_the_same_txs @ HF 6", 1240},
  {"alt_blocks_with_the_same_txs @ HF 5", 1239},
  {"block_with_correct_prev_id_on_wrong_height @ HF 5", 1233},
  {"block_with_correct_prev_id_on_wrong_height @ HF 4", 1231},
  {"gen_alias_too_much_reward @ HF 5", 1227},
  {"alt_blocks_with_the_same_txs @ HF 4", 1224},
  {"gen_alias_too_much_reward @ HF 6", 1223},
  {"gen_alias_too_much_reward @ HF 4", 1216},
  {"escrow_altchain_meta_test<0>", 1214},
  {"hard_fork_1_pos_and_locked_coins", 1201},
  {"chain_switching_when_gindex_spent_in_both_chains @ HF 4", 1198},
  {"escrow_altchain_meta_test<5>", 1198},
  {"chain_switching_when_gindex_spent_in_both_chains @ HF 5", 1197},
  {"escrow_altchain_meta_test<1>", 1196},
  {"chain_switching_when_gindex_spent_in_both_chains @ HF 6", 1192},
  {"escrow_proposal_expiration", 1190},
  {"escrow_altchain_meta_test<6>", 1164},
  {"escrow_altchain_meta_test<4>", 1156},
  {"offers_updating_hack", 1152},
  {"gen_ring_signature_1", 1151},
  {"gen_tx_signatures_are_invalid", 1147},
  {"wallet_and_sweep_below @ HF 3", 1140},
  {"mix_in_spent_outs", 1136},
  {"wallet_watch_only_and_chain_switch @ HF 3", 1127},
  {"packing_outputs_on_pos_minting_wallet @ HF 3", 1123},
  {"gen_broken_attachments", 1117},
  {"hard_fork_2_auditable_addresses_basics @ HF 2", 1114},
  {"escrow_altchain_meta_test<8>", 1112},
  {"hard_fork_2_alias_update_using_old_tx<true>", 1110},
  {"escrow_altchain_meta_test<7>", 1105},
  {"escrow_altchain_meta_test<2>", 1103},
  {"hard_fork_2_auditable_addresses_basics @ HF 3", 1103},
  {"escrow_cancellation_proposal_expiration", 1097},
  {"tx_coinbase_separate_sig_flag @ HF 5", 1097},
  {"wallet_unconfirmed_tx_expiration", 1093},
  {"escrow_proposal_and_accept_expiration", 1090},
  {"hard_fork_2_tx_extra_alias_entry_in_wallet", 1081},
  {"tx_coinbase_separate_sig_flag @ HF 4", 1080},
  {"tx_coinbase_separate_sig_flag @ HF 6", 1080},
  {"hard_fork_2_incorrect_alias_update<true>", 1079},
  {"hard_fork_2_alias_update_using_old_tx<false>", 1071},
  {"random_outs_and_burnt_coins", 1071},
  {"escrow_proposal_not_enough_money", 1066},
  {"escrow_cancellation_acceptance_expiration", 1064},
  {"hardfork_4_pop_tx_from_global_index @ HF 5", 1036},
  {"multisig_wallet_heterogenous_dst", 1032},
  {"hardfork_4_pop_tx_from_global_index @ HF 6", 1029},
  {"gen_pos_extra_nonce @ HF 6", 1026},
  {"hardfork_4_pop_tx_from_global_index @ HF 4", 1026},
  {"wallet_rpc_cold_signing @ HF 3", 1025},
  {"attachment_isolation_test @ HF 6", 1008},
  {"gen_pos_extra_nonce @ HF 5", 1008},
  {"gen_pos_extra_nonce @ HF 4", 1006},
  {"wallet_rpc_hardfork_verification @ HF 5", 976},
  {"gen_alias_tx_no_outs @ HF 5", 902},
  {"gen_alias_tx_no_outs @ HF 6", 883},
  {"gen_alias_tx_no_outs @ HF 4", 873},
  {"gen_alias_too_small_reward @ HF 3", 849},
  {"cumulative_difficulty_adjustment_test_alt", 803},
  {"gen_block_big_major_version", 781},
  {"gen_pos_incorrect_timestamp", 771},
  {"zarcanum_test_n_inputs_validation", 760},
  {"gen_wallet_alias_via_special_wallet_funcs @ HF 3", 755},
  {"cumulative_difficulty_adjustment_test", 711},
  {"gen_alias_in_coinbase @ HF 4", 711},
  {"gen_alias_in_coinbase @ HF 5", 709},
  {"gen_simple_chain_split_1", 700},
  {"gen_alias_in_coinbase @ HF 6", 698},
  {"tx_key_image_pool_conflict", 690},
  {"pos_altblocks_validation @ HF 3", 685},
  {"escrow_altchain_meta_test<3>", 682},
  {"hard_fork_1_checkpoint_basic_test", 682},
  {"gen_tx_unlock_time", 657},
  {"gen_wallet_save_load_and_balance @ HF 0", 657},
  {"offer_sig_validity_in_update_and_cancel", 657},
  {"gen_chain_switch_1", 653},
  {"multisig_and_coinbase", 652},
  {"gen_wallet_decrypted_payload_items", 644},
  {"gen_double_spend_in_the_same_block<true>", 643},
  {"hard_fork_1_bad_pos_source", 640},
  {"mix_attr_tests", 640},
  {"multisig_out_make_and_spent_in_altchain", 636},
  {"gen_double_spend_in_different_blocks<false>", 633},
  {"offer_removing_and_selected_output", 632},
  {"gen_wallet_save_load_and_balance @ HF 2", 629},
  {"gen_wallet_save_load_and_balance @ HF 3", 627},
  {"chain_switching_when_out_spent_in_alt_chain_mixin @ HF 3", 626},
  {"block_reward_in_main_chain_basic @ HF 3", 625},
  {"gen_tx_check_input_unlock_time", 624},
  {"gen_tx_extra_double_entry", 623},
  {"chain_switching_when_out_spent_in_alt_chain_ref_id @ HF 3", 622},
  {"alt_blocks_validation_and_same_new_amount_in_two_txs @ HF 3", 621},
  {"gen_double_spend_in_tx<false>", 616},
  {"gen_double_spend_in_different_chains", 614},
  {"alt_chain_and_block_tx_fee_median @ HF 3", 610},
  {"hard_fork_1_unlock_time_2_in_normal_tx", 608},
  {"hard_fork_2_no_new_structures_before_hf", 608},
  {"hard_fork_1_pos_locked_height_vs_time", 606},
  {"gen_double_spend_in_alt_chain_in_the_same_block<false>", 605},
  {"gen_wallet_mine_pos_block @ HF 3", 604},
  {"multisig_and_altchains", 604},
  {"gen_alias_switch_and_check_block_template @ HF 3", 600},
  {"wallet_unconfimed_tx_balance", 599},
  {"pow_pos_reorganize_specific_case", 598},
  {"gen_double_spend_in_alt_chain_in_different_blocks<false>", 597},
  {"gen_double_spend_in_alt_chain_in_different_blocks<true>", 594},
  {"hard_fork_2_incorrect_alias_update<false>", 594},
  {"offers_tests", 594},
  {"gen_wallet_unlock_by_block_and_by_time", 593},
  {"gen_alias_concurrency_with_switch @ HF 3", 592},
  {"gen_ring_signature_2", 592},
  {"gen_wallet_alias_and_unconfirmed_txs @ HF 3", 591},
  {"gen_wallet_save_load_and_balance @ HF 1", 591},
  {"offers_filtering_1", 590},
  {"offers_multiple_update", 590},
  {"isolate_auditable_and_proof @ HF 3", 588},
  {"gen_alias_strange_data @ HF 3", 587},
  {"gen_double_spend_in_alt_chain_in_the_same_block<true>", 587},
  {"gen_wallet_transfers_and_chain_switch", 587},
  {"hard_fork_1_chain_switch_pow_only", 587},
  {"gen_double_spend_in_the_same_block<false>", 586},
  {"gen_double_spend_in_tx<true>", 585},
  {"gen_wallet_payment_id", 583},
  {"chain_switching_and_tx_with_attachment_blobsize", 580},
  {"multisig_and_checkpoints @ HF 0", 580},
  {"hard_fork_4_consolidated_txs @ HF 3", 579},
  {"multisig_with_same_id_in_pool", 579},
  {"offer_lifecycle_via_tx_pool", 579},
  {"gen_crypted_attachments", 577},
  {"gen_uint_overflow_2", 577},
  {"gen_wallet_selecting_pos_entries", 577},
  {"wallet_chain_switch_with_spending_the_same_ki @ HF 3", 577},
  {"gen_wallet_basic_transfer", 576},
  {"ref_by_id_mixed_inputs_types", 576},
  {"gen_pos_coinstake_already_spent", 575},
  {"gen_wallet_refreshing_on_chain_switch", 574},
  {"pos_mining_with_decoys @ HF 3", 574},
  {"escrow_cancellation_and_tx_order", 573},
  {"offers_expiration_test", 573},
  {"block_reward_in_alt_chain_basic @ HF 3", 572},
  {"escrow_balance", 572},
  {"get_random_outs_test", 572},
  {"multisig_and_unlock_time", 572},
  {"multisig_minimum_sigs", 572},
  {"tx_expiration_time_and_chain_switching", 571},
  {"gen_pos_too_early_pos_block", 570},
  {"gen_wallet_transfers_and_outdated_unconfirmed_txs", 570},
  {"isolate_auditable_and_proof @ HF 2", 570},
  {"gen_checkpoints_set_after_switching_to_altchain", 568},
  {"gen_block_miner_tx_has_2_in @ HF 0", 567},
  {"gen_checkpoints_altchain_far_before_cp", 567},
  {"gen_wallet_oversized_payment_id", 566},
  {"gen_double_spend_in_different_blocks<true>", 565},
  {"block_template_vs_invalid_txs_from_pool", 564},
  {"escrow_zero_amounts", 564},
  {"gen_wallet_refreshing_on_chain_switch_2", 563},
  {"gen_alias_switch_and_tx_pool @ HF 3", 562},
  {"multisig_n_participants_seq_signing", 561},
  {"gen_block_invalid_nonce @ HF 0", 560},
  {"ref_by_id_basics", 560},
  {"wallet_outputs_with_same_key_image", 560},
  {"wallet_rpc_transfer", 560},
  {"tx_pool_semantic_validation @ HF 3", 559},
  {"bad_chain_switching_with_rollback", 557},
  {"gen_tx_mixed_key_offest_not_exist", 557},
  {"multisig_and_checkpoints_bad_txs", 556},
  {"offer_cancellation_with_zero_fee", 556},
  {"gen_checkpoints_invalid_keyimage", 554},
  {"multisig_out_spent_in_altchain_case_b4", 554},
  {"gen_alias_same_alias_in_tx_pool @ HF 3", 552},
  {"gen_wallet_unconfirmed_tx_from_tx_pool", 552},
  {"tx_expiration_time", 552},
  {"alt_blocks_with_the_same_txs @ HF 3", 551},
  {"alt_chain_coins_pow_mined_then_spent", 550},
  {"gen_checkpoints_block_in_future_after_cp", 550},
  {"gen_checkpoints_pos_validation_on_altchain", 549},
  {"gen_tx_invalid_input_amount", 548},
  {"multisig_and_fake_outputs", 547},
  {"gen_wallet_offers_basic", 546},
  {"chain_switching_when_gindex_spent_in_both_chains @ HF 3", 545},
  {"gen_checkpoints_prun_txs_after_blockchain_load", 545},
  {"gen_tx_input_is_not_txin_to_key", 545},
  {"multisig_wallet_ms_to_ms", 545},
  {"gen_tx_has_inputs_no_outputs", 543},
  {"test_blockchain_vs_spent_keyimges", 542},
  {"gen_checkpoints_attachments_basic", 541},
  {"block_with_correct_prev_id_on_wrong_height @ HF 3", 540},
  {"gen_tx_key_offest_points_to_foreign_key", 539},
  {"gen_tx_output_with_zero_amount", 538},
  {"pos_wallet_big_block_test", 538},
  {"gen_checkpoints_altblock_before_and_after_cp", 537},
  {"gen_wallet_offers_size_limit", 537},
  {"gen_alias_update_for_free @ HF 3", 536},
  {"gen_tx_double_key_image", 536},
  {"gen_tx_input_wo_key_offsets", 536},
  {"gen_tx_no_inputs_has_outputs", 536},
  {"fill_tx_rpc_inputs", 535},
  {"wallet_sending_to_integrated_address", 535},
  {"gen_alias_too_much_reward @ HF 3", 534},
  {"gen_tx_key_image_not_derive_from_tx_key", 534},
  {"gen_wallet_unconfirmed_outdated_tx", 534},
  {"gen_block_miner_tx_with_txin_to_key @ HF 0", 533},
  {"gen_block_miner_tx_with_txin_to_key @ HF 3", 533},
  {"tx_expiration_time_and_block_template", 533},
  {"wallet_rpc_integrated_address_transfer", 532},
  {"gen_checkpoints_block_in_future", 531},
  {"gen_tx_txout_to_key_has_invalid_key", 531},
  {"gen_wallet_dust_to_account", 531},
  {"gen_tx_big_version", 528},
  {"test_blockchain_vs_spent_multisig_outs", 528},
  {"gen_block_miner_tx_has_2_in @ HF 3", 526},
  {"gen_no_attchments_in_coinbase_gentime", 525},
  {"gen_alias_tx_no_outs @ HF 3", 524},
  {"gen_no_attchments_in_coinbase @ HF 3", 524},
  {"gen_pos_min_allowed_height", 524},
  {"hardfork_4_wallet_transfer_with_mandatory_mixins @ HF 3", 524},
  {"gen_checkpoints_and_invalid_tx_to_pool", 523},
  {"gen_alias_tx_no_outs @ HF 2", 522},
  {"gen_pos_invalid_coinbase", 522},
  {"gen_tx_key_image_is_invalid", 521},
  {"gen_tx_sender_key_offest_not_exist", 521},
  {"multisig_wallet_same_dst_addr", 521},
  {"gen_alias_tx_no_outs @ HF 0", 520},
  {"gen_alias_tx_no_outs @ HF 1", 520},
  {"hard_fork_1_unlock_time_2_in_coinbase", 520},
  {"multisig_unconfirmed_transfer_and_multiple_scan_pool_calls", 520},
  {"gen_block_invalid_nonce @ HF 3", 519},
  {"gen_pos_extra_nonce @ HF 3", 519},
  {"gen_alias_in_coinbase @ HF 3", 514},
  {"gen_alias_reg_with_locked_money @ HF 1", 505},
  {"gen_alias_reg_with_locked_money @ HF 2", 505},
  {"gen_alias_reg_with_locked_money @ HF 3", 505},
  {"gen_alias_reg_with_locked_money @ HF 5", 505},
  {"gen_alias_reg_with_locked_money @ HF 6", 505},
  {"gen_block_big_major_version @ HF 0", 505},
  {"gen_block_has_invalid_tx @ HF 0", 505},
  {"gen_block_has_invalid_tx @ HF 3", 505},
  {"gen_block_height_is_high @ HF 0", 505},
  {"gen_block_height_is_high @ HF 3", 505},
  {"gen_block_miner_tx_has_2_tx_gen_in @ HF 0", 505},
  {"gen_block_miner_tx_has_no_out @ HF 3", 505},
  {"gen_block_miner_tx_has_out_to_initiator @ HF 0", 505},
  {"gen_block_miner_tx_out_is_big @ HF 3", 505},
  {"gen_block_miner_tx_out_is_small @ HF 0", 505},
  {"gen_block_no_miner_tx @ HF 0", 505},
  {"gen_block_unlock_time_is_high @ HF 3", 505},
  {"gen_block_unlock_time_is_timestamp_in_past @ HF 0", 505},
  {"gen_alias_reg_with_locked_money @ HF 0", 504},
  {"gen_alias_reg_with_locked_money @ HF 4", 504},
  {"gen_block_big_major_version @ HF 3", 504},
  {"gen_block_big_minor_version @ HF 0", 504},
  {"gen_block_big_minor_version @ HF 3", 504},
  {"gen_block_height_is_low @ HF 0", 504},
  {"gen_block_height_is_low @ HF 3", 504},
  {"gen_block_miner_tx_has_2_tx_gen_in @ HF 3", 504},
  {"gen_block_miner_tx_has_no_out @ HF 0", 504},
  {"gen_block_miner_tx_has_out_to_initiator @ HF 3", 504},
  {"gen_block_miner_tx_out_is_big @ HF 0", 504},
  {"gen_block_miner_tx_out_is_small @ HF 3", 504},
  {"gen_block_no_miner_tx @ HF 3", 504},
  {"gen_block_ts_in_future @ HF 0", 504},
  {"gen_block_ts_in_future @ HF 3", 504},
  {"gen_block_unlock_time_is_high @ HF 0", 504},
  {"gen_block_unlock_time_is_low @ HF 0", 504},
  {"gen_block_unlock_time_is_low @ HF 3", 504},
  {"gen_block_unlock_time_is_timestamp_in_future @ HF 0", 504},
  {"gen_block_unlock_time_is_timestamp_in_future @ HF 3", 504},
  {"gen_block_unlock_time_is_timestamp_in_past @ HF 3", 504},
  {"mined_balance_wallet_test", 504},
  {"wallet_rpc_integrated_address", 504},
  {"gen_block_wrong_version_agains_hardfork @ HF 0", 503},
  {"gen_block_wrong_version_agains_hardfork @ HF 3", 503},
  {"gen_tx_no_inputs_no_outputs", 503},
  {"one_block", 503},
  {"wallet_rpc_exchange_suite @ HF 3", 503},
  {"gen_tx_output_is_not_txout_to_key", 502},
};

inline uint64_t get_test_time_ms(std::string_view test_name, uint64_t unknown_ms)
{
  for (const auto& e : k_test_time_hints)
    if (e.name == test_name) return e.ms;
  return unknown_ms;
}

// Unknown tests should be considered the slowest to run first
inline uint64_t get_test_estimated_ms(std::string_view test_name)
{
  static const std::unordered_map<std::string_view, uint64_t> m = []()
  {
    std::unordered_map<std::string_view, uint64_t> r;
    r.reserve(k_test_time_hints.size());
    for (const auto& e : k_test_time_hints)
      r.emplace(e.name, e.ms);
    return r;
  }();

  constexpr uint64_t k_unknown_ms = (std::numeric_limits<uint64_t>::max)() / 4;
  auto it = m.find(test_name);
  return it == m.end() ? k_unknown_ms : it->second;
}