#!/bin/bash

case $1 in
   config)
        cat <<'EOM'
graph_title aliases
graph_vlabel aliases
graph_category daemon
alias_count.label alias_count
EOM
        exit 0;;
esac

printf "alias_count.value "
connectivity_tool --ip=127.0.0.1 --rpc-port=$ZANO_RPC_PORT --timeout=1000 --rpc-get-daemon-info --getinfo-flags-hex="0x0000000000000000" | grep alias_count | cut -d ' ' -f2
