#!/bin/bash

case $1 in
   config)
        cat <<'EOM'
graph_title alt_blocks_count
graph_vlabel alt_blocks_count
graph_category daemon
alt_blocks_count.label alt_blocks_count
EOM
        exit 0;;
esac

printf "alt_blocks_count.value "
connectivity_tool --ip=127.0.0.1 --rpc-port=$ZANO_RPC_PORT --timeout=1000 --rpc-get-daemon-info --getinfo-flags-hex="0x0000000000000000" | grep alt_blocks_count | cut -d ' ' -f2
