#!/bin/bash

case $1 in
   config)
        cat <<'EOM'
graph_title blockchain_data_file_size
graph_vlabel blockchain_data_file_size
graph_category daemon
blockchain_data_file_size.label blockchain_data_file_size 
EOM
        exit 0;;
esac

printf "blockchain_data_file_size.value "
#sudo ls -l /tmp/ttt | cut -d" " -f5
sudo ls -l /root/.Zano/blockchain/data.mdb | cut -d" " -f5
