#!/bin/bash

case $1 in
   config)
        cat <<'EOM'
graph_title blockchain_mdbx_data_file_size
graph_vlabel blockchain_mdbx_data_file_size
graph_category daemon
blockchain_mdbx_data_file_size.label blockchain_mdbx_data_file_size
EOM
        exit 0;;
esac

printf "blockchain_mdbx_data_file_size.value "
sudo ls -l /root/.Zano/blockchain_mdbx_v1/mdbx.dat | cut -d" " -f5
