#!/bin/bash

case $1 in
   config)
        cat <<'EOM'
graph_title db_map_size
graph_vlabel db_map_size
graph_category daemon
db_map_size.label db_map_size

EOM
        exit 0;;
esac

printf "db_map_size.value "
connectivity_tool --ip=127.0.0.1 --rpc_port=$ZANO_RPC_PORT --timeout=1000 --rpc_get_daemon_info --getinfo_flags_hex="0x0000000000010000" | grep db_map_size | cut -d ' ' -f2
