#!/bin/bash

case $1 in
   config)
        cat <<'EOM'
graph_title emission
graph_vlabel emission
graph_category daemon
total_coins.label total_coins
pos_diff_in_coins.label pos_diff_in_coins
EOM
        exit 0;;
esac

printf "total_coins.value "
connectivity_tool --ip=127.0.0.1 --rpc-port=$ZANO_RPC_PORT --timeout=1000 --rpc-get-daemon-info --getinfo-flags-hex="0x0000000000000400" | grep total_coins| cut -d ' ' -f2
printf "pos_diff_in_coins.value "
connectivity_tool --ip=127.0.0.1 --rpc-port=$ZANO_RPC_PORT --timeout=1000 --rpc-get-daemon-info --getinfo-flags-hex="0x0000000000000001" | grep pos_difficulty_in_coins| cut -d ' ' -f2
