#!/bin/bash

case $1 in
   config)
        cat <<'EOM'
graph_title poolstate_lmdb_data_file_size
graph_vlabel poolstate_lmdb_data_file_size
graph_category daemon
poolstate_lmdb_data_file_size.label poolstate_lmdb_data_file_size 
EOM
        exit 0;;
esac

printf "poolstate_lmdb_data_file_size.value "
sudo ls -l /root/.Zano/poolstate_lmdb_v1/data.mdb | cut -d" " -f5
