#!/bin/bash

case $1 in
   config)
        cat <<'EOM'
graph_args --alt-autoscale
graph_title difficulty
graph_vlabel difficulty
graph_category daemon
pos_difficulty.label pos_difficulty

EOM
        exit 0;;
esac

printf "pos_difficulty.value "
connectivity_tool --ip=127.0.0.1 --rpc-port=$ZANO_RPC_PORT --timeout=1000 --rpc-get-daemon-info --getinfo-flags-hex="0x0000000000000001" | grep pos_difficulty | cut -d ' ' -f2
