#!/bin/bash

case $1 in
   config)
        cat <<'EOM'
graph_title difficulty
graph_vlabel difficulty
graph_category daemon
pow_difficulty.label pow_difficulty

EOM
        exit 0;;
esac

printf "pow_difficulty.value "
connectivity_tool --ip=127.0.0.1 --rpc_port=$ZANO_RPC_PORT --timeout=1000 --rpc_get_daemon_info --getinfo_flags_hex="0x0000000000000002" | grep pow_difficulty | cut -d ' ' -f2
