#!/bin/bash

case $1 in
   config)
        cat <<'EOM'
graph_title tx_count
graph_vlabel tx_count
graph_category daemon
tx_count.label tx_count
tx_count.type COUNTER
EOM
        exit 0;;
esac

printf "tx_count.value "
connectivity_tool --ip=127.0.0.1 --rpc-port=$ZANO_RPC_PORT --timeout=1000 --rpc-get-daemon-info --getinfo-flags-hex="0x0000000000000000" | grep tx_count| cut -d ' ' -f2
