#!/bin/bash

case $1 in
   config)
        cat <<'EOM'
graph_args --alt-autoscale
graph_title mixins
graph_vlabel mixins
graph_category transactions
mixins.label mixins

EOM
        exit 0;;
esac

printf "mixins.value "
connectivity_tool --ip=127.0.0.1 --rpc-port=$ZANO_RPC_PORT --timeout=1000 --rpc-get-daemon-info --getinfo-flags-hex="0x0000000000010000" | grep tx_mixin_count | cut -d ' ' -f2
