#!/bin/bash

case $1 in
   config)
        cat <<'EOM'
graph_title tx_pool_size
graph_vlabel tx_pool_size
graph_category daemon
tx_pool_size.label tx_pool_size
EOM
        exit 0;;
esac

printf "tx_pool_size.value "
connectivity_tool --ip=127.0.0.1 --rpc-port=$ZANO_RPC_PORT --timeout=1000 --rpc-get-daemon-info --getinfo-flags-hex="0x0000000000000000" | grep tx_pool_size| cut -d ' ' -f2
